apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ly5bikytd-go-gitops
  description: This is GitOps manifest for ly5bikytd-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ly5bikytd-go
    backstage.io/kubernetes-id: ly5bikytd-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ly5bikytd-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ly5bikytd-go
